version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: debug
    versions:
    - 4.3.1
  - dependency-name: "@types/debug"
    versions:
    - 4.1.5
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.13
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
    - 8.0.2
  - dependency-name: postcss-values-parser
    versions:
    - 4.0.0
    - 5.0.0
  - dependency-name: prettier
    versions:
    - 2.2.1
